### ISSUE TITLE
Get Swerve Drive Working

### ISSUE THREAD

**Issue by epshteinmatthew** [frc3268/ValhallaLib#1]
Assigned to EVERYONE
Swerve currently acts all weird. Leads on the issue include inaccurate reporting of encoders measurements, controller issues, etc. This is a team effort until I can break it down into smaller problems

**Comment by Chargde-Porcupine** [comment]
Refactored

**Comment by weijuwang** [comment]
Can you document the issues in more detail just so we know what exactly it is we need to fix?

**Comment by weijuwang** [comment]
skill isuse

**Comment by Chargde-Porcupine** [comment]
I didn't document this previously because the issue a)changes a lot and b)I was at home
But you bring up a fair point...

**ISSUES WITH SWERVE:**
 - Swerve trying to turn constantly when on joystick input
 - Gear ratio is not correct(as of what is deployed), resulting in the encoders getting off kilter
 - field oriented doesnt work, idk why

**Comment by weijuwang** [comment]
Which file do you think the bugs are in?

**Comment by fernir3268** [comment]
New Update on this: PID may need returning. See post in relevant discord channel.

**Comment by epshteinmatthew** [comment]
Update on PID and gear ratio is successful! Next stop: rotation in place.

**Comment by SailingDreamer** [comment]
The problem could be that the positions of the swerve modules in the code are wrong. This would explain the fact that all swerve modules being set to a 45 degree angle but not in the right direction.

**Comment by epshteinmatthew** [comment]
that's correct. the problem was in the SwerveDriveKinematics object at the top of the SwerveDriveBase file, which had the modules in the incorrect order
